# Site settings
title:       blog.montagmorgen.at
email:       georg.ringer@gmail.com
author:      Georg Ringer
description: "Blog by Georg Ringer, mostly about coding with TYPO3"
baseurl:     ""
url:         "http://blog.montagmorgen.at"

# Google analytics
google_analytics: UA-57411660-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: georgringer
twitter_username: georg_ringer
google_plus_id:
linkedin_username: georgringer
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
permalink: /:year/:month/:day/:title.html
excerpt_separator: <!--more-->